#define ITTD_LOGIC 5
#define ITTD_LOGIC_FRMCLIENLIST 10
#define ITTD_LOGIC_FRMCLIENLIST_CLIENTTEXT 15
#define ITTD_LOGIC_FRMCLIENLIST_MANAGER 20
#define ITTD_LOGIC_FRMCOPYCOUNTRY 25
#define ITTD_LOGIC_FRMCOPYCOUNTRY_DIC 30
#define ITTD_LOGIC_ITTD_COUNTRY_ADMI 35
#define ITTD_LOGIC_ITTD_COUNTRY_ADMI_ONRUN 40

