VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "DogovorRportStub"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_HelpID = 60
Option Explicit

Public DogDate As Date
Attribute DogDate.VB_VarHelpID = 90
Public DogMonth As String
Attribute DogMonth.VB_VarHelpID = 95
Public ClientName As String
Attribute ClientName.VB_VarHelpID = 85
Public FIO As String
Attribute FIO.VB_VarHelpID = 100
Public Reason As String
Attribute Reason.VB_VarHelpID = 120
Public Client As String
Attribute Client.VB_VarHelpID = 80
Public Address As String
Attribute Address.VB_VarHelpID = 70
Public INN As String
Attribute INN.VB_VarHelpID = 105
Public Account As String
Attribute Account.VB_VarHelpID = 65
Public KorAccount As String
Attribute KorAccount.VB_VarHelpID = 110
Public BIK As String
Attribute BIK.VB_VarHelpID = 75
Public Position As String
Attribute Position.VB_VarHelpID = 115
Public Sign As String
Attribute Sign.VB_VarHelpID = 125
