VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "mnuStub"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_HelpID = 1275
Option Explicit

'Класс для инициализации списка состояний


Public Caption As String
Attribute Caption.VB_VarHelpID = 1280
Public Tag As String
Attribute Tag.VB_VarHelpID = 1295
Public Visible As Boolean
Attribute Visible.VB_VarHelpID = 1300
Public Checked As Boolean
Attribute Checked.VB_VarHelpID = 1285
Public Enabled As Boolean
Attribute Enabled.VB_VarHelpID = 1290

